package com.ryanchapin.util.hashgenerator;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.ryanchapin.util.hashgenerator.HashGeneratorTest.HashAlgo;
import com.ryanchapin.util.hashgenerator.HashGeneratorTest.HashTestData;
import com.ryanchapin.util.hashgenerator.HashGeneratorTest.TestDataType;

/**
 * Auto-generated test data
 * 
 * @author Ryan Chapin
 * @since  2015-03-14
 */
public class HashGeneratorTestData {
   
   /** Map to contain the List {@link HashTestData} instances for each data type. */
   public static  Map<TestDataType, List<HashTestData<? extends Object>>> testDataMap;
   
   static {
      testDataMap = new HashMap<TestDataType, List<HashTestData<? extends Object>>>();

      // Each of the following lists contains a HashTestData instance with
      // the source value, it's hash, and the algorithm used to generate that
      // hash.
      List<HashTestData<? extends Object>> byteList      = new ArrayList<HashTestData<? extends Object>>();
      List<HashTestData<? extends Object>> characterList = new ArrayList<HashTestData<? extends Object>>();
      List<HashTestData<? extends Object>> shortList     = new ArrayList<HashTestData<? extends Object>>();
      List<HashTestData<? extends Object>> integerList   = new ArrayList<HashTestData<? extends Object>>();
      List<HashTestData<? extends Object>> longList      = new ArrayList<HashTestData<? extends Object>>();
      List<HashTestData<? extends Object>> floatList     = new ArrayList<HashTestData<? extends Object>>();
      List<HashTestData<? extends Object>> doubleList    = new ArrayList<HashTestData<? extends Object>>();
      List<HashTestData<? extends Object>> stringList    = new ArrayList<HashTestData<? extends Object>>();

      testDataMap.put(TestDataType.BYTE,      byteList);
      testDataMap.put(TestDataType.SHORT,     shortList);
      testDataMap.put(TestDataType.CHARACTER, characterList);
      testDataMap.put(TestDataType.INTEGER,   integerList);
      testDataMap.put(TestDataType.LONG,      longList);
      testDataMap.put(TestDataType.FLOAT,     floatList);
      testDataMap.put(TestDataType.DOUBLE,    doubleList);
      testDataMap.put(TestDataType.STRING,    stringList);
            
      // ----------------------------------------------------------------------
      // All of the code for each of the following HashDataTest instances are
      // dynamically generated by the gen_hashes.sh script in the
      // src/test/resources directory.  See the README.md for full details.
      
      HashTestData<? extends Object> htd_Byte_0 = new HashTestData<Byte>(
         new Byte((byte)-128),
         "5462d67d136c35b5ab71ff1bdb28df0f",
         HashAlgo.MD5SUM);
      byteList.add(htd_Byte_0);
      
      HashTestData<? extends Object> htd_Byte_1 = new HashTestData<Byte>(
         new Byte((byte)-128),
         "e9723cebe688912f684bcd19b48e5bc8efafaf2a",
         HashAlgo.SHA1SUM);
      byteList.add(htd_Byte_1);
      
      HashTestData<? extends Object> htd_Byte_2 = new HashTestData<Byte>(
         new Byte((byte)-128),
         "1d89d17ddf37084f28b17459d47ac655f2f82929c7c537b5210e48fefb659aee",
         HashAlgo.SHA256SUM);
      byteList.add(htd_Byte_2);
      
      HashTestData<? extends Object> htd_Byte_3 = new HashTestData<Byte>(
         new Byte((byte)-128),
         "bb75cc0b5afa59e963a2f375d1020faed4e3bfc59c1486a676ee0d6cf72d4b4a0aab4b25da228e48f5ecde0c2921ad24",
         HashAlgo.SHA384SUM);
      byteList.add(htd_Byte_3);
      
      HashTestData<? extends Object> htd_Byte_4 = new HashTestData<Byte>(
         new Byte((byte)-128),
         "7314787cdf0c7ee33562a4a14e6cd22ee5358dd0c1d04a4c00959f97b41cd2c57db230ca180c82af32ff6fb622a7871b7dfc348b8b35e7fec698c9f7b6c5ec2f",
         HashAlgo.SHA512SUM);
      byteList.add(htd_Byte_4);
      
      HashTestData<? extends Object> htd_Byte_5 = new HashTestData<Byte>(
         new Byte((byte)-23),
         "52722fca814c095200ae1046e72acab5",
         HashAlgo.MD5SUM);
      byteList.add(htd_Byte_5);
      
      HashTestData<? extends Object> htd_Byte_6 = new HashTestData<Byte>(
         new Byte((byte)-23),
         "8915ff14fa1f154b8457c716576353ed1b87997b",
         HashAlgo.SHA1SUM);
      byteList.add(htd_Byte_6);
      
      HashTestData<? extends Object> htd_Byte_7 = new HashTestData<Byte>(
         new Byte((byte)-23),
         "b09e6fc207c159601c9adaf7d44278d102a26a4f21c7f711b2842734da2aa114",
         HashAlgo.SHA256SUM);
      byteList.add(htd_Byte_7);
      
      HashTestData<? extends Object> htd_Byte_8 = new HashTestData<Byte>(
         new Byte((byte)-23),
         "c705bd2f8454dba30122b2b17a48fa00a915a3322d846e9dfb794645c7a26b5d7362de5605169d72fedda1d6ee6143c4",
         HashAlgo.SHA384SUM);
      byteList.add(htd_Byte_8);
      
      HashTestData<? extends Object> htd_Byte_9 = new HashTestData<Byte>(
         new Byte((byte)-23),
         "bb8a017124df73ff06184215b67ed50e462b88ea58745d1b93a0dea378d508662ef6d9ec952ab737a757719b061de68c5ac838db7766c5ce43dfdc5fae596a99",
         HashAlgo.SHA512SUM);
      byteList.add(htd_Byte_9);
      
      HashTestData<? extends Object> htd_Byte_10 = new HashTestData<Byte>(
         new Byte((byte)0),
         "f1d3ff8443297732862df21dc4e57262",
         HashAlgo.MD5SUM);
      byteList.add(htd_Byte_10);
      
      HashTestData<? extends Object> htd_Byte_11 = new HashTestData<Byte>(
         new Byte((byte)0),
         "9069ca78e7450a285173431b3e52c5c25299e473",
         HashAlgo.SHA1SUM);
      byteList.add(htd_Byte_11);
      
      HashTestData<? extends Object> htd_Byte_12 = new HashTestData<Byte>(
         new Byte((byte)0),
         "df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119",
         HashAlgo.SHA256SUM);
      byteList.add(htd_Byte_12);
      
      HashTestData<? extends Object> htd_Byte_13 = new HashTestData<Byte>(
         new Byte((byte)0),
         "394341b7182cd227c5c6b07ef8000cdfd86136c4292b8e576573ad7ed9ae41019f5818b4b971c9effc60e1ad9f1289f0",
         HashAlgo.SHA384SUM);
      byteList.add(htd_Byte_13);
      
      HashTestData<? extends Object> htd_Byte_14 = new HashTestData<Byte>(
         new Byte((byte)0),
         "ec2d57691d9b2d40182ac565032054b7d784ba96b18bcb5be0bb4e70e3fb041eff582c8af66ee50256539f2181d7f9e53627c0189da7e75a4d5ef10ea93b20b3",
         HashAlgo.SHA512SUM);
      byteList.add(htd_Byte_14);
      
      HashTestData<? extends Object> htd_Byte_15 = new HashTestData<Byte>(
         new Byte((byte)87),
         "a03b601751a0b0d53d298a9f7c1c9225",
         HashAlgo.MD5SUM);
      byteList.add(htd_Byte_15);
      
      HashTestData<? extends Object> htd_Byte_16 = new HashTestData<Byte>(
         new Byte((byte)87),
         "943bccfba89834c204b70c2353638b614188434d",
         HashAlgo.SHA1SUM);
      byteList.add(htd_Byte_16);
      
      HashTestData<? extends Object> htd_Byte_17 = new HashTestData<Byte>(
         new Byte((byte)87),
         "97efc1907815f13e6a02d4149a09e9a5389388ed6def2c1260cfec26d3b19f3f",
         HashAlgo.SHA256SUM);
      byteList.add(htd_Byte_17);
      
      HashTestData<? extends Object> htd_Byte_18 = new HashTestData<Byte>(
         new Byte((byte)87),
         "52c9ddc2457210e7e34515dddc3f6df149081f3312e1dac9e85dce62ec5f525115335de534f9198e58359d0bd307d234",
         HashAlgo.SHA384SUM);
      byteList.add(htd_Byte_18);
      
      HashTestData<? extends Object> htd_Byte_19 = new HashTestData<Byte>(
         new Byte((byte)87),
         "c045a8d165e47a5fb1c85aa44a44892240edac73536e03ca1106ba9b68eaf4068d5be929c5ad3937018fa7d74444a8c8f82346c49308b30ec7e04066de1e4fb6",
         HashAlgo.SHA512SUM);
      byteList.add(htd_Byte_19);
      
      HashTestData<? extends Object> htd_Byte_20 = new HashTestData<Byte>(
         new Byte((byte)127),
         "1df2364d502d1d8a765b114f0da56207",
         HashAlgo.MD5SUM);
      byteList.add(htd_Byte_20);
      
      HashTestData<? extends Object> htd_Byte_21 = new HashTestData<Byte>(
         new Byte((byte)127),
         "1554d73dacf97447a3a2d46fe172b4fe11692f02",
         HashAlgo.SHA1SUM);
      byteList.add(htd_Byte_21);
      
      HashTestData<? extends Object> htd_Byte_22 = new HashTestData<Byte>(
         new Byte((byte)127),
         "8226952884d05e8a0d647a443de86906f567aab8d72fe8f844a1ce4b255bb396",
         HashAlgo.SHA256SUM);
      byteList.add(htd_Byte_22);
      
      HashTestData<? extends Object> htd_Byte_23 = new HashTestData<Byte>(
         new Byte((byte)127),
         "b30875214d5a7963c3f25ebbed2b732a165241c75020f0993f5249a02256a335963f144a5115354f40ec6236a40cfabf",
         HashAlgo.SHA384SUM);
      byteList.add(htd_Byte_23);
      
      HashTestData<? extends Object> htd_Byte_24 = new HashTestData<Byte>(
         new Byte((byte)127),
         "4532b8ca36b5e35fdfd864e787092bebd4614cbd9a5ff67c6424c1e013c62d43eedd5e9d7bd8d788217f93c8b6089e08cc35df745e8b4e17202bea72fa9e8b32",
         HashAlgo.SHA512SUM);
      byteList.add(htd_Byte_24);
      
      HashTestData<? extends Object> htd_Character_25 = new HashTestData<Character>(
         new Character('a'),
         "8b41d42570561ecee5c798bc15046194",
         HashAlgo.MD5SUM);
      characterList.add(htd_Character_25);
      
      HashTestData<? extends Object> htd_Character_26 = new HashTestData<Character>(
         new Character('a'),
         "92985ba6cfd97df5289f882a73c16297b9c48809",
         HashAlgo.SHA1SUM);
      characterList.add(htd_Character_26);
      
      HashTestData<? extends Object> htd_Character_27 = new HashTestData<Character>(
         new Character('a'),
         "d2febf3079d64fcc48205885b66974fbecac6162a3e75761b082c228e364dd7e",
         HashAlgo.SHA256SUM);
      characterList.add(htd_Character_27);
      
      HashTestData<? extends Object> htd_Character_28 = new HashTestData<Character>(
         new Character('a'),
         "20976dd47a9fb1f29fdf2214889d164af7e21c24ed2688448d93ca5d36cfd134d83e4fe35f617a842a014834451c24a5",
         HashAlgo.SHA384SUM);
      characterList.add(htd_Character_28);
      
      HashTestData<? extends Object> htd_Character_29 = new HashTestData<Character>(
         new Character('a'),
         "ab0b17020fcf4929609a476793be300ab00e1a16db2dedc6380ac164943d5d0c5ce4abeb9686278e92d31c982fb4208f995b5f2d22ada145b313e9095b43a215",
         HashAlgo.SHA512SUM);
      characterList.add(htd_Character_29);
      
      HashTestData<? extends Object> htd_Character_30 = new HashTestData<Character>(
         new Character('B'),
         "91446ac941ef79c7b553ed9285ef2f73",
         HashAlgo.MD5SUM);
      characterList.add(htd_Character_30);
      
      HashTestData<? extends Object> htd_Character_31 = new HashTestData<Character>(
         new Character('B'),
         "90193db35eb7b197cf6c6203fdc77ab9f1ddc1d5",
         HashAlgo.SHA1SUM);
      characterList.add(htd_Character_31);
      
      HashTestData<? extends Object> htd_Character_32 = new HashTestData<Character>(
         new Character('B'),
         "825ac1bb838d399fb1ba55a6247e2c8c7a0c3ec25898f3c94dbfb51fa6e73951",
         HashAlgo.SHA256SUM);
      characterList.add(htd_Character_32);
      
      HashTestData<? extends Object> htd_Character_33 = new HashTestData<Character>(
         new Character('B'),
         "0526b658cfce2a23d38b96ead62ef4f5f85ca35acb7d18318bc80c03bb8676d5886518deb8ef8dc671dacc15b5201986",
         HashAlgo.SHA384SUM);
      characterList.add(htd_Character_33);
      
      HashTestData<? extends Object> htd_Character_34 = new HashTestData<Character>(
         new Character('B'),
         "73f87a70dba673ee1d2e86419d05681d5e93fb070d8591f94e29fe67ac4eb37b82093c070b023bbd70d0799ea5acad2b2f142d1328ca4f03451b12c97b69d41e",
         HashAlgo.SHA512SUM);
      characterList.add(htd_Character_34);
      
      HashTestData<? extends Object> htd_Character_35 = new HashTestData<Character>(
         new Character('F'),
         "9485552ad99c3647741e813f265ac3a8",
         HashAlgo.MD5SUM);
      characterList.add(htd_Character_35);
      
      HashTestData<? extends Object> htd_Character_36 = new HashTestData<Character>(
         new Character('F'),
         "b822d892963b017185e91a5db1a058759b0f56bb",
         HashAlgo.SHA1SUM);
      characterList.add(htd_Character_36);
      
      HashTestData<? extends Object> htd_Character_37 = new HashTestData<Character>(
         new Character('F'),
         "514970ce425bbbe11b969e5cd683f4c1b7722f7f026b45006c53a8031b2fc32e",
         HashAlgo.SHA256SUM);
      characterList.add(htd_Character_37);
      
      HashTestData<? extends Object> htd_Character_38 = new HashTestData<Character>(
         new Character('F'),
         "3d430dd4e3ff1a6d4e236734f294efa94ad2b0b6b80c4e22aa80af00c4b1c178ae6871062aa282bfcb76fab0afb5a482",
         HashAlgo.SHA384SUM);
      characterList.add(htd_Character_38);
      
      HashTestData<? extends Object> htd_Character_39 = new HashTestData<Character>(
         new Character('F'),
         "f9b97ebd2856c518cfd8da84180662733d09aac0dfcbc309a722bef867c0d4ec51fae6fd87fcee6f66b274fb6711f23ade4ca264f72bfe569c9ae093efcf5561",
         HashAlgo.SHA512SUM);
      characterList.add(htd_Character_39);
      
      HashTestData<? extends Object> htd_Character_40 = new HashTestData<Character>(
         new Character('#'),
         "66bc172b52faf05d4dc19e1532b65030",
         HashAlgo.MD5SUM);
      characterList.add(htd_Character_40);
      
      HashTestData<? extends Object> htd_Character_41 = new HashTestData<Character>(
         new Character('#'),
         "b5ab517f7f92cc8604f9e08ebf09e545a06c454d",
         HashAlgo.SHA1SUM);
      characterList.add(htd_Character_41);
      
      HashTestData<? extends Object> htd_Character_42 = new HashTestData<Character>(
         new Character('#'),
         "6870f86f6560dd5b0d0a47d0ae89df6a96b6a47a6258940060d75ff759634158",
         HashAlgo.SHA256SUM);
      characterList.add(htd_Character_42);
      
      HashTestData<? extends Object> htd_Character_43 = new HashTestData<Character>(
         new Character('#'),
         "55b758be19ab5194574ed9a4e0b6f38abaf0018d785c849c4893cf051405230f8e460b0250214db2f9cc01935f2c9a00",
         HashAlgo.SHA384SUM);
      characterList.add(htd_Character_43);
      
      HashTestData<? extends Object> htd_Character_44 = new HashTestData<Character>(
         new Character('#'),
         "3d149cb4d2df0b8d7488079060c5bd7638fb7dca551249642cacbefef5e8a608605326de0565b77215bd3a9274ab0bb342634b7d55dcb3e1bc988c4f6e9838bf",
         HashAlgo.SHA512SUM);
      characterList.add(htd_Character_44);
      
      HashTestData<? extends Object> htd_Character_45 = new HashTestData<Character>(
         new Character('~'),
         "9293aee561348d2b7aba7d100f49bef0",
         HashAlgo.MD5SUM);
      characterList.add(htd_Character_45);
      
      HashTestData<? extends Object> htd_Character_46 = new HashTestData<Character>(
         new Character('~'),
         "075de86e694dc4a33f693bb41bc0e73b00e6d2d9",
         HashAlgo.SHA1SUM);
      characterList.add(htd_Character_46);
      
      HashTestData<? extends Object> htd_Character_47 = new HashTestData<Character>(
         new Character('~'),
         "4bc492dadd3c70359abc6f8a94a1f305fd7716be261aa605c99eb2ddff4f06e0",
         HashAlgo.SHA256SUM);
      characterList.add(htd_Character_47);
      
      HashTestData<? extends Object> htd_Character_48 = new HashTestData<Character>(
         new Character('~'),
         "52dbc7da7c09497e0a19ba870d4bf20e258fca53cc713c6b203dcc3f13bb70fb45eb7d4c8400c252190dad5da4f8ac0f",
         HashAlgo.SHA384SUM);
      characterList.add(htd_Character_48);
      
      HashTestData<? extends Object> htd_Character_49 = new HashTestData<Character>(
         new Character('~'),
         "ea96ab77ad4944503973973db5d679b2377852f91cbb4bbe8ae6043d74c21232da48788f6e2c0f323e0187dd0a8057c1d631eb6fc2adf7916dbc8bb32d5a08e4",
         HashAlgo.SHA512SUM);
      characterList.add(htd_Character_49);
      
      HashTestData<? extends Object> htd_Double_50 = new HashTestData<Double>(
         new Double(0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004940656458412465441765687928682213723650598026143247644255856825006755072702087518652998363616359923797965646954457177309266567103559397963987747960107818781263007131903114045278458171678489821036887186360569987307230500063874091535649843873124733972731696151400317153853980741262385655911710266585566867681870395603106249319452715914924553293054565444011274801297099995419319894090804165633245247571478690147267801593552386115501348035264934720193790268107107491703332226844753335720832431936092382893458368060106011506169809753078342277318329247904982524730776375927247874656084778203734469699533647017972677717585125660551199131504891101451037862738167250955837389733598993664809941164205702637090279242767544565229087538682506419718265533447265625D),
         "fa5ad9a8557e5a84cf23e52d3d3adf77",
         HashAlgo.MD5SUM);
      doubleList.add(htd_Double_50);
      
      HashTestData<? extends Object> htd_Double_51 = new HashTestData<Double>(
         new Double(0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004940656458412465441765687928682213723650598026143247644255856825006755072702087518652998363616359923797965646954457177309266567103559397963987747960107818781263007131903114045278458171678489821036887186360569987307230500063874091535649843873124733972731696151400317153853980741262385655911710266585566867681870395603106249319452715914924553293054565444011274801297099995419319894090804165633245247571478690147267801593552386115501348035264934720193790268107107491703332226844753335720832431936092382893458368060106011506169809753078342277318329247904982524730776375927247874656084778203734469699533647017972677717585125660551199131504891101451037862738167250955837389733598993664809941164205702637090279242767544565229087538682506419718265533447265625D),
         "cb473678976f425d6ec1339838f11011007ad27d",
         HashAlgo.SHA1SUM);
      doubleList.add(htd_Double_51);
      
      HashTestData<? extends Object> htd_Double_52 = new HashTestData<Double>(
         new Double(0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004940656458412465441765687928682213723650598026143247644255856825006755072702087518652998363616359923797965646954457177309266567103559397963987747960107818781263007131903114045278458171678489821036887186360569987307230500063874091535649843873124733972731696151400317153853980741262385655911710266585566867681870395603106249319452715914924553293054565444011274801297099995419319894090804165633245247571478690147267801593552386115501348035264934720193790268107107491703332226844753335720832431936092382893458368060106011506169809753078342277318329247904982524730776375927247874656084778203734469699533647017972677717585125660551199131504891101451037862738167250955837389733598993664809941164205702637090279242767544565229087538682506419718265533447265625D),
         "cd2662154e6d76b2b2b92e70c0cac3ccf534f9b74eb5b89819ec509083d00a50",
         HashAlgo.SHA256SUM);
      doubleList.add(htd_Double_52);
      
      HashTestData<? extends Object> htd_Double_53 = new HashTestData<Double>(
         new Double(0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004940656458412465441765687928682213723650598026143247644255856825006755072702087518652998363616359923797965646954457177309266567103559397963987747960107818781263007131903114045278458171678489821036887186360569987307230500063874091535649843873124733972731696151400317153853980741262385655911710266585566867681870395603106249319452715914924553293054565444011274801297099995419319894090804165633245247571478690147267801593552386115501348035264934720193790268107107491703332226844753335720832431936092382893458368060106011506169809753078342277318329247904982524730776375927247874656084778203734469699533647017972677717585125660551199131504891101451037862738167250955837389733598993664809941164205702637090279242767544565229087538682506419718265533447265625D),
         "30f61d4b94e1d74e6a751248ff2007f715a16cd214365fcef3e5751664a568475eccd842d1396aa5cfa83f5b9d20c586",
         HashAlgo.SHA384SUM);
      doubleList.add(htd_Double_53);
      
      HashTestData<? extends Object> htd_Double_54 = new HashTestData<Double>(
         new Double(0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004940656458412465441765687928682213723650598026143247644255856825006755072702087518652998363616359923797965646954457177309266567103559397963987747960107818781263007131903114045278458171678489821036887186360569987307230500063874091535649843873124733972731696151400317153853980741262385655911710266585566867681870395603106249319452715914924553293054565444011274801297099995419319894090804165633245247571478690147267801593552386115501348035264934720193790268107107491703332226844753335720832431936092382893458368060106011506169809753078342277318329247904982524730776375927247874656084778203734469699533647017972677717585125660551199131504891101451037862738167250955837389733598993664809941164205702637090279242767544565229087538682506419718265533447265625D),
         "df9c478c05321087b50a1d239b4aab290e9b793252758e706e24312aed21c29072285e436a20c3c6227f99b73638f0414fba5835586fee4e19231c1ec56d58ee",
         HashAlgo.SHA512SUM);
      doubleList.add(htd_Double_54);
      
      HashTestData<? extends Object> htd_Double_55 = new HashTestData<Double>(
         new Double(-9082741083.082347869873046875D),
         "dc7faa0a5bf8b674a3c4e1b5310dc1ba",
         HashAlgo.MD5SUM);
      doubleList.add(htd_Double_55);
      
      HashTestData<? extends Object> htd_Double_56 = new HashTestData<Double>(
         new Double(-9082741083.082347869873046875D),
         "c1dd4e92a9d3d7fa37e63eeefca6e860be95b267",
         HashAlgo.SHA1SUM);
      doubleList.add(htd_Double_56);
      
      HashTestData<? extends Object> htd_Double_57 = new HashTestData<Double>(
         new Double(-9082741083.082347869873046875D),
         "3df1fd4a93261d17725ac8de0bb2ebd696aff3128f5d2dd50056c668dd85602f",
         HashAlgo.SHA256SUM);
      doubleList.add(htd_Double_57);
      
      HashTestData<? extends Object> htd_Double_58 = new HashTestData<Double>(
         new Double(-9082741083.082347869873046875D),
         "53f499c6caeb86e4eee58502739f2211f548b2489f239254eccb3620f62f9df42bd75d08b948dbe3a5ca58e26d74bd8b",
         HashAlgo.SHA384SUM);
      doubleList.add(htd_Double_58);
      
      HashTestData<? extends Object> htd_Double_59 = new HashTestData<Double>(
         new Double(-9082741083.082347869873046875D),
         "cde564e5ac0d45ff2cd18b9e3cd4966055147ac515eac88f291cdfc8bcf306d0f6c2ae96986538ed2b1fc63febd82f2911504908cb291c0c8492866bda36ee94",
         HashAlgo.SHA512SUM);
      doubleList.add(htd_Double_59);
      
      HashTestData<? extends Object> htd_Double_60 = new HashTestData<Double>(
         new Double(0D),
         "7dea362b3fac8e00956a4952a3d4f474",
         HashAlgo.MD5SUM);
      doubleList.add(htd_Double_60);
      
      HashTestData<? extends Object> htd_Double_61 = new HashTestData<Double>(
         new Double(0D),
         "05fe405753166f125559e7c9ac558654f107c7e9",
         HashAlgo.SHA1SUM);
      doubleList.add(htd_Double_61);
      
      HashTestData<? extends Object> htd_Double_62 = new HashTestData<Double>(
         new Double(0D),
         "af5570f5a1810b7af78caf4bc70a660f0df51e42baf91d4de5b2328de0e83dfc",
         HashAlgo.SHA256SUM);
      doubleList.add(htd_Double_62);
      
      HashTestData<? extends Object> htd_Double_63 = new HashTestData<Double>(
         new Double(0D),
         "7c2db09d310ece0b36d50c86e4c3e6641684948cd6fc03262b0d0ed91a6cfbc3cd5affd396c1f85fd0a109b103364b19",
         HashAlgo.SHA384SUM);
      doubleList.add(htd_Double_63);
      
      HashTestData<? extends Object> htd_Double_64 = new HashTestData<Double>(
         new Double(0D),
         "1b7409ccf0d5a34d3a77eaabfa9fe27427655be9297127ee9522aa1bf4046d4f945983678169cb1a7348edcac47ef0d9e2c924130e5bcc5f0d94937852c42f1b",
         HashAlgo.SHA512SUM);
      doubleList.add(htd_Double_64);
      
      HashTestData<? extends Object> htd_Double_65 = new HashTestData<Double>(
         new Double(2340823.987567239440977573394775390625D),
         "8ab253d62f66616e56db1aaab36dfa20",
         HashAlgo.MD5SUM);
      doubleList.add(htd_Double_65);
      
      HashTestData<? extends Object> htd_Double_66 = new HashTestData<Double>(
         new Double(2340823.987567239440977573394775390625D),
         "60946c8abe83f1c8b821ae4778d5f20d0f74af47",
         HashAlgo.SHA1SUM);
      doubleList.add(htd_Double_66);
      
      HashTestData<? extends Object> htd_Double_67 = new HashTestData<Double>(
         new Double(2340823.987567239440977573394775390625D),
         "483796405e84729b3d69c31d1f26169fcac8f879a208fe8632dc6b07bde6dec2",
         HashAlgo.SHA256SUM);
      doubleList.add(htd_Double_67);
      
      HashTestData<? extends Object> htd_Double_68 = new HashTestData<Double>(
         new Double(2340823.987567239440977573394775390625D),
         "643cb86c20dc8188440310107bd5aa00e068d95a8ad57000511e557d8eccd0ca683ea56ee367a6b5623b9750dd929040",
         HashAlgo.SHA384SUM);
      doubleList.add(htd_Double_68);
      
      HashTestData<? extends Object> htd_Double_69 = new HashTestData<Double>(
         new Double(2340823.987567239440977573394775390625D),
         "96a8470592598bccc51b87b667cf83809ab02a985484dfffa9f323220890fcb666aa8788f97e4eb3a7121482e77c97a4d6d2b231bc3505dc5111af2970321711",
         HashAlgo.SHA512SUM);
      doubleList.add(htd_Double_69);
      
      HashTestData<? extends Object> htd_Double_70 = new HashTestData<Double>(
         new Double(179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368D),
         "5801bdc2d76b6ea9b7091a5026caf731",
         HashAlgo.MD5SUM);
      doubleList.add(htd_Double_70);
      
      HashTestData<? extends Object> htd_Double_71 = new HashTestData<Double>(
         new Double(179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368D),
         "de1e67a299928343dd050a52fde96feb3f1f3028",
         HashAlgo.SHA1SUM);
      doubleList.add(htd_Double_71);
      
      HashTestData<? extends Object> htd_Double_72 = new HashTestData<Double>(
         new Double(179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368D),
         "88dc7b5696598bb5bb3b0a3100300db6fa58d87cac4cee380462588cf04b9015",
         HashAlgo.SHA256SUM);
      doubleList.add(htd_Double_72);
      
      HashTestData<? extends Object> htd_Double_73 = new HashTestData<Double>(
         new Double(179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368D),
         "0e085d3e63f1e57034cbf71da947eecba416699d4e9f706fcddf85b310523a95049053aa684c927c82fb684fdf932b86",
         HashAlgo.SHA384SUM);
      doubleList.add(htd_Double_73);
      
      HashTestData<? extends Object> htd_Double_74 = new HashTestData<Double>(
         new Double(179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368D),
         "526471b4812bebe071cd31917871e6ab85f14614e70ddd8f0b3fba5b20c494bfad238df229b83fb9610e44cc316c3e7d9f681c9ec5d89e11096b329772dab8de",
         HashAlgo.SHA512SUM);
      doubleList.add(htd_Double_74);
      
      HashTestData<? extends Object> htd_Float_75 = new HashTestData<Float>(
         new Float(340282350000000000000000000000000000000F),
         "8a18aeed5caff58aa370b52e36dcbc3f",
         HashAlgo.MD5SUM);
      floatList.add(htd_Float_75);
      
      HashTestData<? extends Object> htd_Float_76 = new HashTestData<Float>(
         new Float(340282350000000000000000000000000000000F),
         "26ae45cabd7d1bd5ea3d6511d0fdbf5f196f8ad5",
         HashAlgo.SHA1SUM);
      floatList.add(htd_Float_76);
      
      HashTestData<? extends Object> htd_Float_77 = new HashTestData<Float>(
         new Float(340282350000000000000000000000000000000F),
         "dde5bcff31e3b2e6085239af1da9827447d0705e8500092ab6bdf699d819c231",
         HashAlgo.SHA256SUM);
      floatList.add(htd_Float_77);
      
      HashTestData<? extends Object> htd_Float_78 = new HashTestData<Float>(
         new Float(340282350000000000000000000000000000000F),
         "abcb3e56775ccb74b66bea7c00e18dbffae54f4d4a3ca2bb7707694a289575b0f9c18624724c4372e4b778f56cf3824f",
         HashAlgo.SHA384SUM);
      floatList.add(htd_Float_78);
      
      HashTestData<? extends Object> htd_Float_79 = new HashTestData<Float>(
         new Float(340282350000000000000000000000000000000F),
         "6a1319fcbf8e4c0150d8d12ef4a76e3aa75a14da4aa0838dbe564f64b01bf6c037f40787d2ebf837843f7489d07f1704d9f9b43c74dec3b15dfc0ccf9c77be4b",
         HashAlgo.SHA512SUM);
      floatList.add(htd_Float_79);
      
      HashTestData<? extends Object> htd_Float_80 = new HashTestData<Float>(
         new Float(-234.72346F),
         "94937552c204754f10ebeedaf526a2c2",
         HashAlgo.MD5SUM);
      floatList.add(htd_Float_80);
      
      HashTestData<? extends Object> htd_Float_81 = new HashTestData<Float>(
         new Float(-234.72346F),
         "a18736c490eb0a515288b52f13f16bc95e836ce1",
         HashAlgo.SHA1SUM);
      floatList.add(htd_Float_81);
      
      HashTestData<? extends Object> htd_Float_82 = new HashTestData<Float>(
         new Float(-234.72346F),
         "99e6966e86d37fcc84a3c84b1a91ed9700a9322c85ea358556e9b84f5a5a1777",
         HashAlgo.SHA256SUM);
      floatList.add(htd_Float_82);
      
      HashTestData<? extends Object> htd_Float_83 = new HashTestData<Float>(
         new Float(-234.72346F),
         "582072ceb705186aaf1062b30ca4d06b73cedc0a60dc4bd1ae439d6c8d2e7cb5d70c63c63b92b5d9091a4dcbdb46598b",
         HashAlgo.SHA384SUM);
      floatList.add(htd_Float_83);
      
      HashTestData<? extends Object> htd_Float_84 = new HashTestData<Float>(
         new Float(-234.72346F),
         "5d8b5ab07a368b21d4217a8c541c3400961df4fef763702fea9445db601d3f615376da8e5862a552a650fbef92ee792ba98ba1788c5d7bf2012385314d95cf25",
         HashAlgo.SHA512SUM);
      floatList.add(htd_Float_84);
      
      HashTestData<? extends Object> htd_Float_85 = new HashTestData<Float>(
         new Float(0.0F),
         "f1d3ff8443297732862df21dc4e57262",
         HashAlgo.MD5SUM);
      floatList.add(htd_Float_85);
      
      HashTestData<? extends Object> htd_Float_86 = new HashTestData<Float>(
         new Float(0.0F),
         "9069ca78e7450a285173431b3e52c5c25299e473",
         HashAlgo.SHA1SUM);
      floatList.add(htd_Float_86);
      
      HashTestData<? extends Object> htd_Float_87 = new HashTestData<Float>(
         new Float(0.0F),
         "df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119",
         HashAlgo.SHA256SUM);
      floatList.add(htd_Float_87);
      
      HashTestData<? extends Object> htd_Float_88 = new HashTestData<Float>(
         new Float(0.0F),
         "394341b7182cd227c5c6b07ef8000cdfd86136c4292b8e576573ad7ed9ae41019f5818b4b971c9effc60e1ad9f1289f0",
         HashAlgo.SHA384SUM);
      floatList.add(htd_Float_88);
      
      HashTestData<? extends Object> htd_Float_89 = new HashTestData<Float>(
         new Float(0.0F),
         "ec2d57691d9b2d40182ac565032054b7d784ba96b18bcb5be0bb4e70e3fb041eff582c8af66ee50256539f2181d7f9e53627c0189da7e75a4d5ef10ea93b20b3",
         HashAlgo.SHA512SUM);
      floatList.add(htd_Float_89);
      
      HashTestData<? extends Object> htd_Float_90 = new HashTestData<Float>(
         new Float(232864336F),
         "2fb5625c3ce85f4eb455922e58f6ee00",
         HashAlgo.MD5SUM);
      floatList.add(htd_Float_90);
      
      HashTestData<? extends Object> htd_Float_91 = new HashTestData<Float>(
         new Float(232864336F),
         "f040bce0098f185bfdf7e5d88bc8672c6221efb9",
         HashAlgo.SHA1SUM);
      floatList.add(htd_Float_91);
      
      HashTestData<? extends Object> htd_Float_92 = new HashTestData<Float>(
         new Float(232864336F),
         "7d1cb40ede9f14400187af650e6e893fcb6ad0f6441d0b86aa2e7e546209c2c1",
         HashAlgo.SHA256SUM);
      floatList.add(htd_Float_92);
      
      HashTestData<? extends Object> htd_Float_93 = new HashTestData<Float>(
         new Float(232864336F),
         "92e993e2a75940bffbb822c7b1a6b3de824c5745098d95066903f72bf09ba201f9e2dc087343bdc1b943d1f0c22ac938",
         HashAlgo.SHA384SUM);
      floatList.add(htd_Float_93);
      
      HashTestData<? extends Object> htd_Float_94 = new HashTestData<Float>(
         new Float(232864336F),
         "d2ff719782d4fd0c4269a18dffbff2b757092370e4f2cdad5f966b2f7bdd70cf89fe0d42255fa903927a6beeaa1d9487c1d8d462bb9f7dd58710257bf8986183",
         HashAlgo.SHA512SUM);
      floatList.add(htd_Float_94);
      
      HashTestData<? extends Object> htd_Float_95 = new HashTestData<Float>(
         new Float(340282350000000000000000000000000000000F),
         "8a18aeed5caff58aa370b52e36dcbc3f",
         HashAlgo.MD5SUM);
      floatList.add(htd_Float_95);
      
      HashTestData<? extends Object> htd_Float_96 = new HashTestData<Float>(
         new Float(340282350000000000000000000000000000000F),
         "26ae45cabd7d1bd5ea3d6511d0fdbf5f196f8ad5",
         HashAlgo.SHA1SUM);
      floatList.add(htd_Float_96);
      
      HashTestData<? extends Object> htd_Float_97 = new HashTestData<Float>(
         new Float(340282350000000000000000000000000000000F),
         "dde5bcff31e3b2e6085239af1da9827447d0705e8500092ab6bdf699d819c231",
         HashAlgo.SHA256SUM);
      floatList.add(htd_Float_97);
      
      HashTestData<? extends Object> htd_Float_98 = new HashTestData<Float>(
         new Float(340282350000000000000000000000000000000F),
         "abcb3e56775ccb74b66bea7c00e18dbffae54f4d4a3ca2bb7707694a289575b0f9c18624724c4372e4b778f56cf3824f",
         HashAlgo.SHA384SUM);
      floatList.add(htd_Float_98);
      
      HashTestData<? extends Object> htd_Float_99 = new HashTestData<Float>(
         new Float(340282350000000000000000000000000000000F),
         "6a1319fcbf8e4c0150d8d12ef4a76e3aa75a14da4aa0838dbe564f64b01bf6c037f40787d2ebf837843f7489d07f1704d9f9b43c74dec3b15dfc0ccf9c77be4b",
         HashAlgo.SHA512SUM);
      floatList.add(htd_Float_99);
      
      HashTestData<? extends Object> htd_Integer_100 = new HashTestData<Integer>(
         new Integer(-2147483648),
         "b879f7666e5b73c7de7ebc4032b52f70",
         HashAlgo.MD5SUM);
      integerList.add(htd_Integer_100);
      
      HashTestData<? extends Object> htd_Integer_101 = new HashTestData<Integer>(
         new Integer(-2147483648),
         "e1798367d1b1ed54425e99f790a986c1fe939414",
         HashAlgo.SHA1SUM);
      integerList.add(htd_Integer_101);
      
      HashTestData<? extends Object> htd_Integer_102 = new HashTestData<Integer>(
         new Integer(-2147483648),
         "50c8ba3a6170f0a2fb6736ece8a603576ef6309a35e810911599bc6211b554a9",
         HashAlgo.SHA256SUM);
      integerList.add(htd_Integer_102);
      
      HashTestData<? extends Object> htd_Integer_103 = new HashTestData<Integer>(
         new Integer(-2147483648),
         "f73a245ff6d0800421050e6281160c5d74919caebfc86d02e11bcdc2a60ec391fa9c3a9e688c820ec83abbd258ddafd7",
         HashAlgo.SHA384SUM);
      integerList.add(htd_Integer_103);
      
      HashTestData<? extends Object> htd_Integer_104 = new HashTestData<Integer>(
         new Integer(-2147483648),
         "df45732659aad83aae5edfc59bab32796c708eb61e9be97ab94abbf7616d9b3a36fba7c84aedcfe1857b54edb41e169b1959d7d7d69d8349a38d516947172ce0",
         HashAlgo.SHA512SUM);
      integerList.add(htd_Integer_104);
      
      HashTestData<? extends Object> htd_Integer_105 = new HashTestData<Integer>(
         new Integer(-256),
         "ec106a8574ce7e60014e79363c9e6a2b",
         HashAlgo.MD5SUM);
      integerList.add(htd_Integer_105);
      
      HashTestData<? extends Object> htd_Integer_106 = new HashTestData<Integer>(
         new Integer(-256),
         "04336836571352041fc1a2dda7cc73d3d23c4c57",
         HashAlgo.SHA1SUM);
      integerList.add(htd_Integer_106);
      
      HashTestData<? extends Object> htd_Integer_107 = new HashTestData<Integer>(
         new Integer(-256),
         "6fc6f4524161c3ae0d316812d7088e3fcd372023edaea2d7821093be40ae1060",
         HashAlgo.SHA256SUM);
      integerList.add(htd_Integer_107);
      
      HashTestData<? extends Object> htd_Integer_108 = new HashTestData<Integer>(
         new Integer(-256),
         "801b6ed11c4e6a3c000c0f72626f4f90e6fcc9427cf09cc30a64b2593c052d022ff1fbfb64c17a6d6e94a1c55b80b23c",
         HashAlgo.SHA384SUM);
      integerList.add(htd_Integer_108);
      
      HashTestData<? extends Object> htd_Integer_109 = new HashTestData<Integer>(
         new Integer(-256),
         "bf5b46831db754c12cb535378d5e99ffa432bccf91b22d5c071ebb4ed7601b9fb237ac18913a2443e36c8341cda59a468055163ed90a4f2e46575149388213f2",
         HashAlgo.SHA512SUM);
      integerList.add(htd_Integer_109);
      
      HashTestData<? extends Object> htd_Integer_110 = new HashTestData<Integer>(
         new Integer(0),
         "f1d3ff8443297732862df21dc4e57262",
         HashAlgo.MD5SUM);
      integerList.add(htd_Integer_110);
      
      HashTestData<? extends Object> htd_Integer_111 = new HashTestData<Integer>(
         new Integer(0),
         "9069ca78e7450a285173431b3e52c5c25299e473",
         HashAlgo.SHA1SUM);
      integerList.add(htd_Integer_111);
      
      HashTestData<? extends Object> htd_Integer_112 = new HashTestData<Integer>(
         new Integer(0),
         "df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119",
         HashAlgo.SHA256SUM);
      integerList.add(htd_Integer_112);
      
      HashTestData<? extends Object> htd_Integer_113 = new HashTestData<Integer>(
         new Integer(0),
         "394341b7182cd227c5c6b07ef8000cdfd86136c4292b8e576573ad7ed9ae41019f5818b4b971c9effc60e1ad9f1289f0",
         HashAlgo.SHA384SUM);
      integerList.add(htd_Integer_113);
      
      HashTestData<? extends Object> htd_Integer_114 = new HashTestData<Integer>(
         new Integer(0),
         "ec2d57691d9b2d40182ac565032054b7d784ba96b18bcb5be0bb4e70e3fb041eff582c8af66ee50256539f2181d7f9e53627c0189da7e75a4d5ef10ea93b20b3",
         HashAlgo.SHA512SUM);
      integerList.add(htd_Integer_114);
      
      HashTestData<? extends Object> htd_Integer_115 = new HashTestData<Integer>(
         new Integer(191867248),
         "2f89c71363913e17de4f22e0e98b734b",
         HashAlgo.MD5SUM);
      integerList.add(htd_Integer_115);
      
      HashTestData<? extends Object> htd_Integer_116 = new HashTestData<Integer>(
         new Integer(191867248),
         "82831ff840c298fc2b30b12c3da184a59534d72f",
         HashAlgo.SHA1SUM);
      integerList.add(htd_Integer_116);
      
      HashTestData<? extends Object> htd_Integer_117 = new HashTestData<Integer>(
         new Integer(191867248),
         "adba58157aac85217c63c5474e5cf01c3945e205c0db70b0e052121cd13e321b",
         HashAlgo.SHA256SUM);
      integerList.add(htd_Integer_117);
      
      HashTestData<? extends Object> htd_Integer_118 = new HashTestData<Integer>(
         new Integer(191867248),
         "8857c706444d30f5760b5e77abec54b0ce369a9cbdd150dde82d964e312771adccfaec2ae27d68f5bbbe3e7eb590491e",
         HashAlgo.SHA384SUM);
      integerList.add(htd_Integer_118);
      
      HashTestData<? extends Object> htd_Integer_119 = new HashTestData<Integer>(
         new Integer(191867248),
         "a2e602e9ddf65216af4cf5d7b898fd61f223d030338a9acca316b7bfd344decf98c090ceb49c0f7663d723ccce510fc38fd3e1bba94e5466e8de729cffd41b6a",
         HashAlgo.SHA512SUM);
      integerList.add(htd_Integer_119);
      
      HashTestData<? extends Object> htd_Integer_120 = new HashTestData<Integer>(
         new Integer(2147483647),
         "37497ad6a0c4f123cd1a39278afc6869",
         HashAlgo.MD5SUM);
      integerList.add(htd_Integer_120);
      
      HashTestData<? extends Object> htd_Integer_121 = new HashTestData<Integer>(
         new Integer(2147483647),
         "6c28217eecdb75ac5378d20243029696f5e633a1",
         HashAlgo.SHA1SUM);
      integerList.add(htd_Integer_121);
      
      HashTestData<? extends Object> htd_Integer_122 = new HashTestData<Integer>(
         new Integer(2147483647),
         "24ae0d93f1af72addc019182fae1ab44547a1e84758785745f4358373eab1960",
         HashAlgo.SHA256SUM);
      integerList.add(htd_Integer_122);
      
      HashTestData<? extends Object> htd_Integer_123 = new HashTestData<Integer>(
         new Integer(2147483647),
         "75d155cd3e36b9c5c385002cf4953ae2e044e0f2012d01010be8ac8f30a092b5d893506394767cb02ff0613eb613c2e6",
         HashAlgo.SHA384SUM);
      integerList.add(htd_Integer_123);
      
      HashTestData<? extends Object> htd_Integer_124 = new HashTestData<Integer>(
         new Integer(2147483647),
         "645df4e5231da736306efcda918a07c530c97bcc51f7eceb297b8396214c3036a9d08f70e44637ca8558597ca61d59e89f99583004dddcc2b01854b2a0e0566e",
         HashAlgo.SHA512SUM);
      integerList.add(htd_Integer_124);
      
      HashTestData<? extends Object> htd_Long_125 = new HashTestData<Long>(
         new Long(9223372036854775807L),
         "bd5f6598b2d2cd7f130ba3e152116ff7",
         HashAlgo.MD5SUM);
      longList.add(htd_Long_125);
      
      HashTestData<? extends Object> htd_Long_126 = new HashTestData<Long>(
         new Long(9223372036854775807L),
         "bf7f9f8d6e0a3426aef3f0ce773e69e85821efc7",
         HashAlgo.SHA1SUM);
      longList.add(htd_Long_126);
      
      HashTestData<? extends Object> htd_Long_127 = new HashTestData<Long>(
         new Long(9223372036854775807L),
         "c624eebf5b9282431fc4e19c3c707a012275e198d3a077dcd36a7b74e4a804ad",
         HashAlgo.SHA256SUM);
      longList.add(htd_Long_127);
      
      HashTestData<? extends Object> htd_Long_128 = new HashTestData<Long>(
         new Long(9223372036854775807L),
         "ddfe5a9e0659c196434c9d1b8a098cda10c8ce89d4c160374cf781847a5b143d4ab889651516e201cd89f2d5416afbda",
         HashAlgo.SHA384SUM);
      longList.add(htd_Long_128);
      
      HashTestData<? extends Object> htd_Long_129 = new HashTestData<Long>(
         new Long(9223372036854775807L),
         "f48eaadddca1083f42f340f4ad0ab5bf7e50d9f7b6fec01807e12cef9bb0c014506c6393155095bf4ea4963f409b8db58fb17f0f2c5887824b53aa7cc69dc8b3",
         HashAlgo.SHA512SUM);
      longList.add(htd_Long_129);
      
      HashTestData<? extends Object> htd_Long_130 = new HashTestData<Long>(
         new Long(-36028797018963968L),
         "8c64b2b91eaedcae7dfda9b43ca4f62b",
         HashAlgo.MD5SUM);
      longList.add(htd_Long_130);
      
      HashTestData<? extends Object> htd_Long_131 = new HashTestData<Long>(
         new Long(-36028797018963968L),
         "101201ec9be0c94da1aabacf9050452d531db7b6",
         HashAlgo.SHA1SUM);
      longList.add(htd_Long_131);
      
      HashTestData<? extends Object> htd_Long_132 = new HashTestData<Long>(
         new Long(-36028797018963968L),
         "006ce6768bf58dcecb91e0b0957b7e71adbb24e2fafd6e0762fc3b51daae8c65",
         HashAlgo.SHA256SUM);
      longList.add(htd_Long_132);
      
      HashTestData<? extends Object> htd_Long_133 = new HashTestData<Long>(
         new Long(-36028797018963968L),
         "8963d18e89e6463da925a55e1508cfe020e7d1f6b38ee2331e4ad2795ce4f9a8b48a005d85c820ee3db7f150dbe869c7",
         HashAlgo.SHA384SUM);
      longList.add(htd_Long_133);
      
      HashTestData<? extends Object> htd_Long_134 = new HashTestData<Long>(
         new Long(-36028797018963968L),
         "46db6a85707d1394778a41b054941701e3cfd93ec390fe7f156565d916981ca1dfe9d3dbbe1c2f380881c96aa1b9f2bbe6b567303c6fa3633ca0431df3ba81a9",
         HashAlgo.SHA512SUM);
      longList.add(htd_Long_134);
      
      HashTestData<? extends Object> htd_Long_135 = new HashTestData<Long>(
         new Long(0L),
         "7dea362b3fac8e00956a4952a3d4f474",
         HashAlgo.MD5SUM);
      longList.add(htd_Long_135);
      
      HashTestData<? extends Object> htd_Long_136 = new HashTestData<Long>(
         new Long(0L),
         "05fe405753166f125559e7c9ac558654f107c7e9",
         HashAlgo.SHA1SUM);
      longList.add(htd_Long_136);
      
      HashTestData<? extends Object> htd_Long_137 = new HashTestData<Long>(
         new Long(0L),
         "af5570f5a1810b7af78caf4bc70a660f0df51e42baf91d4de5b2328de0e83dfc",
         HashAlgo.SHA256SUM);
      longList.add(htd_Long_137);
      
      HashTestData<? extends Object> htd_Long_138 = new HashTestData<Long>(
         new Long(0L),
         "7c2db09d310ece0b36d50c86e4c3e6641684948cd6fc03262b0d0ed91a6cfbc3cd5affd396c1f85fd0a109b103364b19",
         HashAlgo.SHA384SUM);
      longList.add(htd_Long_138);
      
      HashTestData<? extends Object> htd_Long_139 = new HashTestData<Long>(
         new Long(0L),
         "1b7409ccf0d5a34d3a77eaabfa9fe27427655be9297127ee9522aa1bf4046d4f945983678169cb1a7348edcac47ef0d9e2c924130e5bcc5f0d94937852c42f1b",
         HashAlgo.SHA512SUM);
      longList.add(htd_Long_139);
      
      HashTestData<? extends Object> htd_Long_140 = new HashTestData<Long>(
         new Long(2305843009213693952L),
         "beb49121e6b2d95eb429c1641ae31f64",
         HashAlgo.MD5SUM);
      longList.add(htd_Long_140);
      
      HashTestData<? extends Object> htd_Long_141 = new HashTestData<Long>(
         new Long(2305843009213693952L),
         "0aa60933f90adb707f898d201ff9ec9abf6cb156",
         HashAlgo.SHA1SUM);
      longList.add(htd_Long_141);
      
      HashTestData<? extends Object> htd_Long_142 = new HashTestData<Long>(
         new Long(2305843009213693952L),
         "9d4ac218fb54041e3a70a8e14db1ea1af9f570f4842b4702ef9323f1ad8f0ec4",
         HashAlgo.SHA256SUM);
      longList.add(htd_Long_142);
      
      HashTestData<? extends Object> htd_Long_143 = new HashTestData<Long>(
         new Long(2305843009213693952L),
         "222060d2f13d5736702c122971e7aef8b1417c704014fe161a08da9a94bb563c248aeb06b35a48334c82a156997574da",
         HashAlgo.SHA384SUM);
      longList.add(htd_Long_143);
      
      HashTestData<? extends Object> htd_Long_144 = new HashTestData<Long>(
         new Long(2305843009213693952L),
         "52b0c754e4d2e495544ddfea552df85fb3127fcf6e54f7aacb57e3e6a20be5821d8e707eedb2c22b39b3222ff489d289c9ffb3a85ff8fd6f645a86c8a5a2b1ec",
         HashAlgo.SHA512SUM);
      longList.add(htd_Long_144);
      
      HashTestData<? extends Object> htd_Long_145 = new HashTestData<Long>(
         new Long(9223372036854775807L),
         "bd5f6598b2d2cd7f130ba3e152116ff7",
         HashAlgo.MD5SUM);
      longList.add(htd_Long_145);
      
      HashTestData<? extends Object> htd_Long_146 = new HashTestData<Long>(
         new Long(9223372036854775807L),
         "bf7f9f8d6e0a3426aef3f0ce773e69e85821efc7",
         HashAlgo.SHA1SUM);
      longList.add(htd_Long_146);
      
      HashTestData<? extends Object> htd_Long_147 = new HashTestData<Long>(
         new Long(9223372036854775807L),
         "c624eebf5b9282431fc4e19c3c707a012275e198d3a077dcd36a7b74e4a804ad",
         HashAlgo.SHA256SUM);
      longList.add(htd_Long_147);
      
      HashTestData<? extends Object> htd_Long_148 = new HashTestData<Long>(
         new Long(9223372036854775807L),
         "ddfe5a9e0659c196434c9d1b8a098cda10c8ce89d4c160374cf781847a5b143d4ab889651516e201cd89f2d5416afbda",
         HashAlgo.SHA384SUM);
      longList.add(htd_Long_148);
      
      HashTestData<? extends Object> htd_Long_149 = new HashTestData<Long>(
         new Long(9223372036854775807L),
         "f48eaadddca1083f42f340f4ad0ab5bf7e50d9f7b6fec01807e12cef9bb0c014506c6393155095bf4ea4963f409b8db58fb17f0f2c5887824b53aa7cc69dc8b3",
         HashAlgo.SHA512SUM);
      longList.add(htd_Long_149);
      
      HashTestData<? extends Object> htd_Short_150 = new HashTestData<Short>(
         new Short((short)-32768),
         "8a0d2739b9b12c0f423fe65867a44dfa",
         HashAlgo.MD5SUM);
      shortList.add(htd_Short_150);
      
      HashTestData<? extends Object> htd_Short_151 = new HashTestData<Short>(
         new Short((short)-32768),
         "57861808d2a312156b08dc2be35767511f486691",
         HashAlgo.SHA1SUM);
      shortList.add(htd_Short_151);
      
      HashTestData<? extends Object> htd_Short_152 = new HashTestData<Short>(
         new Short((short)-32768),
         "0ebcd32a9685f0ca0f41bb358cb021a7ed39613d57a5aeec90d419179370c732",
         HashAlgo.SHA256SUM);
      shortList.add(htd_Short_152);
      
      HashTestData<? extends Object> htd_Short_153 = new HashTestData<Short>(
         new Short((short)-32768),
         "7a05cf3b92d7e8e3f591cc16bded9809f556545da7fbeceeb8f309250b755a9eff4250c15ed80e3e3110e493460bbac2",
         HashAlgo.SHA384SUM);
      shortList.add(htd_Short_153);
      
      HashTestData<? extends Object> htd_Short_154 = new HashTestData<Short>(
         new Short((short)-32768),
         "ba8ab52ed1b5a9c76d54c8230bd57e7a62ab31badd4aefbf37ae6b4c1dbd153982d4c450cd5e9b07863e5273c9f0f8b9e155b44f4b2b5005e2fb455db56babbd",
         HashAlgo.SHA512SUM);
      shortList.add(htd_Short_154);
      
      HashTestData<? extends Object> htd_Short_155 = new HashTestData<Short>(
         new Short((short)-647),
         "315241607c0a2e0d2edbfdfa8907083b",
         HashAlgo.MD5SUM);
      shortList.add(htd_Short_155);
      
      HashTestData<? extends Object> htd_Short_156 = new HashTestData<Short>(
         new Short((short)-647),
         "32d7b124262a27d620df88defa3cc35fc06bbe50",
         HashAlgo.SHA1SUM);
      shortList.add(htd_Short_156);
      
      HashTestData<? extends Object> htd_Short_157 = new HashTestData<Short>(
         new Short((short)-647),
         "94ad8b57b7126290bc223917050b4d364aec9ffc38f1eb712b7aec24fff8a2b4",
         HashAlgo.SHA256SUM);
      shortList.add(htd_Short_157);
      
      HashTestData<? extends Object> htd_Short_158 = new HashTestData<Short>(
         new Short((short)-647),
         "169c476eeba79e4ee3754a1a6e7d30a76a80a6da4c56f33c5cb1b492e183d150978575548eb5d1ad7b6c5c21bef27d7f",
         HashAlgo.SHA384SUM);
      shortList.add(htd_Short_158);
      
      HashTestData<? extends Object> htd_Short_159 = new HashTestData<Short>(
         new Short((short)-647),
         "0ca25dabdcc2992501ef8ae3ce714b9661312dbb99a1154e48bf5430533ebcffa37e2a4ea07d942ad33570ef0f428b94ba80bf4f64902475c1e99eac2176c29f",
         HashAlgo.SHA512SUM);
      shortList.add(htd_Short_159);
      
      HashTestData<? extends Object> htd_Short_160 = new HashTestData<Short>(
         new Short((short)0),
         "f1d3ff8443297732862df21dc4e57262",
         HashAlgo.MD5SUM);
      shortList.add(htd_Short_160);
      
      HashTestData<? extends Object> htd_Short_161 = new HashTestData<Short>(
         new Short((short)0),
         "9069ca78e7450a285173431b3e52c5c25299e473",
         HashAlgo.SHA1SUM);
      shortList.add(htd_Short_161);
      
      HashTestData<? extends Object> htd_Short_162 = new HashTestData<Short>(
         new Short((short)0),
         "df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119",
         HashAlgo.SHA256SUM);
      shortList.add(htd_Short_162);
      
      HashTestData<? extends Object> htd_Short_163 = new HashTestData<Short>(
         new Short((short)0),
         "394341b7182cd227c5c6b07ef8000cdfd86136c4292b8e576573ad7ed9ae41019f5818b4b971c9effc60e1ad9f1289f0",
         HashAlgo.SHA384SUM);
      shortList.add(htd_Short_163);
      
      HashTestData<? extends Object> htd_Short_164 = new HashTestData<Short>(
         new Short((short)0),
         "ec2d57691d9b2d40182ac565032054b7d784ba96b18bcb5be0bb4e70e3fb041eff582c8af66ee50256539f2181d7f9e53627c0189da7e75a4d5ef10ea93b20b3",
         HashAlgo.SHA512SUM);
      shortList.add(htd_Short_164);
      
      HashTestData<? extends Object> htd_Short_165 = new HashTestData<Short>(
         new Short((short)6487),
         "b8344f2173df68dc1a00e2bf3d16a62e",
         HashAlgo.MD5SUM);
      shortList.add(htd_Short_165);
      
      HashTestData<? extends Object> htd_Short_166 = new HashTestData<Short>(
         new Short((short)6487),
         "f828876be20b11e2c606f5c80fd11706d0147ba8",
         HashAlgo.SHA1SUM);
      shortList.add(htd_Short_166);
      
      HashTestData<? extends Object> htd_Short_167 = new HashTestData<Short>(
         new Short((short)6487),
         "35c73c5a22f143083a232df641ed2af13246fbc850bb670df0db3a6d05c13753",
         HashAlgo.SHA256SUM);
      shortList.add(htd_Short_167);
      
      HashTestData<? extends Object> htd_Short_168 = new HashTestData<Short>(
         new Short((short)6487),
         "e497c2c302cd305567f60519c700fa63a883c05606a21db572558c8ef6cafe40bfdc13c911f3b55f175f90a251b08036",
         HashAlgo.SHA384SUM);
      shortList.add(htd_Short_168);
      
      HashTestData<? extends Object> htd_Short_169 = new HashTestData<Short>(
         new Short((short)6487),
         "c50caaf83c01aeeb9f7fa333fff65ab1b2d1f8dfd4b862ad915611bccf30fbd9a57be64a6d11b252c3be60ce7b167463233f5f2b070bde0f2cda0761bdbd1bfb",
         HashAlgo.SHA512SUM);
      shortList.add(htd_Short_169);
      
      HashTestData<? extends Object> htd_Short_170 = new HashTestData<Short>(
         new Short((short)32767),
         "d99effdd19323addae49a0f6b0a32c4c",
         HashAlgo.MD5SUM);
      shortList.add(htd_Short_170);
      
      HashTestData<? extends Object> htd_Short_171 = new HashTestData<Short>(
         new Short((short)32767),
         "74ffd82b14ecc5f779b2b9966ee242eb17728587",
         HashAlgo.SHA1SUM);
      shortList.add(htd_Short_171);
      
      HashTestData<? extends Object> htd_Short_172 = new HashTestData<Short>(
         new Short((short)32767),
         "0ef58c180b0a1c291073268769e7d968f7489859cda0a1dcd61eb77996c53cfe",
         HashAlgo.SHA256SUM);
      shortList.add(htd_Short_172);
      
      HashTestData<? extends Object> htd_Short_173 = new HashTestData<Short>(
         new Short((short)32767),
         "7fd59b8bb9a9abbe1d9c0d26481adee793b52be2a8035674eada9c991261cacae1bfc78af7b6576947b21982363c8ecf",
         HashAlgo.SHA384SUM);
      shortList.add(htd_Short_173);
      
      HashTestData<? extends Object> htd_Short_174 = new HashTestData<Short>(
         new Short((short)32767),
         "42164ba6fbbdc8531334089468832c43f204c3c877ae39544647fb30cf7617ff457f2fc92acb50d52e139882921d521fe30230191ceaa952e0292ed3ff0b6fc5",
         HashAlgo.SHA512SUM);
      shortList.add(htd_Short_174);
      
      HashTestData<? extends Object> htd_String_175 = new HashTestData<String>(
         new String("Here is a String that is human readable.  It is a lot easier to read than the random Strings that comprise the rest of this map, no?"),
         "9b3ee6a4cbc285b814a65c991a40ca73",
         HashAlgo.MD5SUM);
      stringList.add(htd_String_175);
      
      HashTestData<? extends Object> htd_String_176 = new HashTestData<String>(
         new String("Here is a String that is human readable.  It is a lot easier to read than the random Strings that comprise the rest of this map, no?"),
         "a31d6d824a76c3351f74cf7c75858ba4c7808512",
         HashAlgo.SHA1SUM);
      stringList.add(htd_String_176);
      
      HashTestData<? extends Object> htd_String_177 = new HashTestData<String>(
         new String("Here is a String that is human readable.  It is a lot easier to read than the random Strings that comprise the rest of this map, no?"),
         "123cc01adb43ec37e25d5f134cbb14dbadf80761c3b98e6c8a2f4e878ee2e963",
         HashAlgo.SHA256SUM);
      stringList.add(htd_String_177);
      
      HashTestData<? extends Object> htd_String_178 = new HashTestData<String>(
         new String("Here is a String that is human readable.  It is a lot easier to read than the random Strings that comprise the rest of this map, no?"),
         "ffa39843241c60cc604f810e55c71f5452eca97613fbdee95c286baa68654b3e002b3bf81034f97e7f94bff6a54f757c",
         HashAlgo.SHA384SUM);
      stringList.add(htd_String_178);
      
      HashTestData<? extends Object> htd_String_179 = new HashTestData<String>(
         new String("Here is a String that is human readable.  It is a lot easier to read than the random Strings that comprise the rest of this map, no?"),
         "7138c9722064098fb4614ec008526ec0a6194e057337ef647b1715f6a41ada3ff8bcbfd1557377e76f214630699d40bcb88021ed1e3b7a5fa33684af7ae1f009",
         HashAlgo.SHA512SUM);
      stringList.add(htd_String_179);
      
      HashTestData<? extends Object> htd_String_180 = new HashTestData<String>(
         new String("8EOTMO,9<R*.s[e3s;n.I/ipJsAkedF>i82]ezG$BzJ9/c`kQw\"07ByH#zR\"~xo3x#7&iEdQ\"Lf>C#YHqMG.@$J7GHlb3.2J(bT@N4fLq?pqkCz`uDsWW;,FBo#_1a&"),
         "7f2a05bca955b7f633efa672cad66a6e",
         HashAlgo.MD5SUM);
      stringList.add(htd_String_180);
      
      HashTestData<? extends Object> htd_String_181 = new HashTestData<String>(
         new String("8EOTMO,9<R*.s[e3s;n.I/ipJsAkedF>i82]ezG$BzJ9/c`kQw\"07ByH#zR\"~xo3x#7&iEdQ\"Lf>C#YHqMG.@$J7GHlb3.2J(bT@N4fLq?pqkCz`uDsWW;,FBo#_1a&"),
         "593cdf102a80e1a238e1d6cdcf08145e16333af9",
         HashAlgo.SHA1SUM);
      stringList.add(htd_String_181);
      
      HashTestData<? extends Object> htd_String_182 = new HashTestData<String>(
         new String("8EOTMO,9<R*.s[e3s;n.I/ipJsAkedF>i82]ezG$BzJ9/c`kQw\"07ByH#zR\"~xo3x#7&iEdQ\"Lf>C#YHqMG.@$J7GHlb3.2J(bT@N4fLq?pqkCz`uDsWW;,FBo#_1a&"),
         "c1509aea7b726805c8accd7fcc8df994dbe0473dbb6af716200fb45cc97ff285",
         HashAlgo.SHA256SUM);
      stringList.add(htd_String_182);
      
      HashTestData<? extends Object> htd_String_183 = new HashTestData<String>(
         new String("8EOTMO,9<R*.s[e3s;n.I/ipJsAkedF>i82]ezG$BzJ9/c`kQw\"07ByH#zR\"~xo3x#7&iEdQ\"Lf>C#YHqMG.@$J7GHlb3.2J(bT@N4fLq?pqkCz`uDsWW;,FBo#_1a&"),
         "370a8429f95ef71d961eab4db0f8d274bd7094bf7325ee3ab06b44100ddc40c130e1cf5d02e236e9e17fb9e4e8e0c3ef",
         HashAlgo.SHA384SUM);
      stringList.add(htd_String_183);
      
      HashTestData<? extends Object> htd_String_184 = new HashTestData<String>(
         new String("8EOTMO,9<R*.s[e3s;n.I/ipJsAkedF>i82]ezG$BzJ9/c`kQw\"07ByH#zR\"~xo3x#7&iEdQ\"Lf>C#YHqMG.@$J7GHlb3.2J(bT@N4fLq?pqkCz`uDsWW;,FBo#_1a&"),
         "0eec470bf87266c62f8342c18a15bcf44966056f95c8f86914f3cdb6c00d116676aba252f464d45220060776c85e3c88d6529019bfd2de949c042cb4ad39caa4",
         HashAlgo.SHA512SUM);
      stringList.add(htd_String_184);
      
      HashTestData<? extends Object> htd_String_185 = new HashTestData<String>(
         new String("L`%xA9CT|Wj|HpER|~rv]wc`qI#z*i&{'14GP4Yr*IE>#8ipXhH>Z|_1@FyKawbHcaIkI0#JHkzb*&[`vDJl`[_r$H1$T_?@\"(GR@(,I^U9+A0_]w*PqD5:,Is1'@u#z"),
         "2f4e8fdeb48d45942cb3820b22503566",
         HashAlgo.MD5SUM);
      stringList.add(htd_String_185);
      
      HashTestData<? extends Object> htd_String_186 = new HashTestData<String>(
         new String("L`%xA9CT|Wj|HpER|~rv]wc`qI#z*i&{'14GP4Yr*IE>#8ipXhH>Z|_1@FyKawbHcaIkI0#JHkzb*&[`vDJl`[_r$H1$T_?@\"(GR@(,I^U9+A0_]w*PqD5:,Is1'@u#z"),
         "01cb1e4e0055374e74335f05ca928e95d7caeeb2",
         HashAlgo.SHA1SUM);
      stringList.add(htd_String_186);
      
      HashTestData<? extends Object> htd_String_187 = new HashTestData<String>(
         new String("L`%xA9CT|Wj|HpER|~rv]wc`qI#z*i&{'14GP4Yr*IE>#8ipXhH>Z|_1@FyKawbHcaIkI0#JHkzb*&[`vDJl`[_r$H1$T_?@\"(GR@(,I^U9+A0_]w*PqD5:,Is1'@u#z"),
         "833a7ee9efd9fb7f4594e6f63edefa85fc2879fe13cfdc9d60d2417b5f1e782d",
         HashAlgo.SHA256SUM);
      stringList.add(htd_String_187);
      
      HashTestData<? extends Object> htd_String_188 = new HashTestData<String>(
         new String("L`%xA9CT|Wj|HpER|~rv]wc`qI#z*i&{'14GP4Yr*IE>#8ipXhH>Z|_1@FyKawbHcaIkI0#JHkzb*&[`vDJl`[_r$H1$T_?@\"(GR@(,I^U9+A0_]w*PqD5:,Is1'@u#z"),
         "7ba18152ae0c954715661c57c1908c5ed29c77f66f400fdcf0c622c45cc0c1ddd750ed95c33d91eebf00c253b0e742a8",
         HashAlgo.SHA384SUM);
      stringList.add(htd_String_188);
      
      HashTestData<? extends Object> htd_String_189 = new HashTestData<String>(
         new String("L`%xA9CT|Wj|HpER|~rv]wc`qI#z*i&{'14GP4Yr*IE>#8ipXhH>Z|_1@FyKawbHcaIkI0#JHkzb*&[`vDJl`[_r$H1$T_?@\"(GR@(,I^U9+A0_]w*PqD5:,Is1'@u#z"),
         "d0385ec84a037ad6dc7cf0e57a08d90451319db6af1ce4685b6e29330cca84fe8b4cfdab549c8cd4d61598135fafa15779fccbfae83b9d1712a75ba7fa7d1d63",
         HashAlgo.SHA512SUM);
      stringList.add(htd_String_189);
      
      HashTestData<? extends Object> htd_String_190 = new HashTestData<String>(
         new String("et83qQS&T{Ask{'!3$/RnLzn<DHGtBmQRq?Uf~j)9]1JbRJd/.|55BY{8o0c/u&?q>5<BosYlT/sk8x#(:$u5c!Vlsw\"^_`G`7]]b`3N+q$OV..6]HSpA3srw*jq]`("),
         "88cd79b97a7524349e44104d7fc0f3ad",
         HashAlgo.MD5SUM);
      stringList.add(htd_String_190);
      
      HashTestData<? extends Object> htd_String_191 = new HashTestData<String>(
         new String("et83qQS&T{Ask{'!3$/RnLzn<DHGtBmQRq?Uf~j)9]1JbRJd/.|55BY{8o0c/u&?q>5<BosYlT/sk8x#(:$u5c!Vlsw\"^_`G`7]]b`3N+q$OV..6]HSpA3srw*jq]`("),
         "8b4131c31cb94bdfb9dffd5ae6ca821d0d313955",
         HashAlgo.SHA1SUM);
      stringList.add(htd_String_191);
      
      HashTestData<? extends Object> htd_String_192 = new HashTestData<String>(
         new String("et83qQS&T{Ask{'!3$/RnLzn<DHGtBmQRq?Uf~j)9]1JbRJd/.|55BY{8o0c/u&?q>5<BosYlT/sk8x#(:$u5c!Vlsw\"^_`G`7]]b`3N+q$OV..6]HSpA3srw*jq]`("),
         "e6c89470e0a303220e61a78d799b1bf5e1c0864a3c6b782ea06e1164d5afe7ec",
         HashAlgo.SHA256SUM);
      stringList.add(htd_String_192);
      
      HashTestData<? extends Object> htd_String_193 = new HashTestData<String>(
         new String("et83qQS&T{Ask{'!3$/RnLzn<DHGtBmQRq?Uf~j)9]1JbRJd/.|55BY{8o0c/u&?q>5<BosYlT/sk8x#(:$u5c!Vlsw\"^_`G`7]]b`3N+q$OV..6]HSpA3srw*jq]`("),
         "0878ecc4e2320640868ab8961ea47f2f87b7906fad3fef69f6cc5cd9a7606d7c077e6a68126a69b01cdd6d56acb892a4",
         HashAlgo.SHA384SUM);
      stringList.add(htd_String_193);
      
      HashTestData<? extends Object> htd_String_194 = new HashTestData<String>(
         new String("et83qQS&T{Ask{'!3$/RnLzn<DHGtBmQRq?Uf~j)9]1JbRJd/.|55BY{8o0c/u&?q>5<BosYlT/sk8x#(:$u5c!Vlsw\"^_`G`7]]b`3N+q$OV..6]HSpA3srw*jq]`("),
         "b16bd116fb8250df6064f84c01e24166b6b1fd1048282178fe8cf68e43f50ba5ead1676ae6c522954602d466309179b4e39a7b0355db2c0a60d2e93090c39511",
         HashAlgo.SHA512SUM);
      stringList.add(htd_String_194);
      
      HashTestData<? extends Object> htd_String_195 = new HashTestData<String>(
         new String("g3&ElAY%T(JQEH|k{D~zDXoxPqA\"R<y5oE>w#IOc4%%xD'x|y9@OM;_F/gi1<_}]#7%\"Y'P8wyjARsn2+E.~7lAf{>o(Z|?EbP&rF^>>Q3wiyP,}sas1\"OSi^2W(J)t$"),
         "0d5135e90153707303d099fbe597d739",
         HashAlgo.MD5SUM);
      stringList.add(htd_String_195);
      
      HashTestData<? extends Object> htd_String_196 = new HashTestData<String>(
         new String("g3&ElAY%T(JQEH|k{D~zDXoxPqA\"R<y5oE>w#IOc4%%xD'x|y9@OM;_F/gi1<_}]#7%\"Y'P8wyjARsn2+E.~7lAf{>o(Z|?EbP&rF^>>Q3wiyP,}sas1\"OSi^2W(J)t$"),
         "df9b8897b2ff0ddd1d2c24e173316ddef4782b21",
         HashAlgo.SHA1SUM);
      stringList.add(htd_String_196);
      
      HashTestData<? extends Object> htd_String_197 = new HashTestData<String>(
         new String("g3&ElAY%T(JQEH|k{D~zDXoxPqA\"R<y5oE>w#IOc4%%xD'x|y9@OM;_F/gi1<_}]#7%\"Y'P8wyjARsn2+E.~7lAf{>o(Z|?EbP&rF^>>Q3wiyP,}sas1\"OSi^2W(J)t$"),
         "30e51380019787ca8cea7f6b64706e1021d428827b896c9b16d81393c6b4e60f",
         HashAlgo.SHA256SUM);
      stringList.add(htd_String_197);
      
      HashTestData<? extends Object> htd_String_198 = new HashTestData<String>(
         new String("g3&ElAY%T(JQEH|k{D~zDXoxPqA\"R<y5oE>w#IOc4%%xD'x|y9@OM;_F/gi1<_}]#7%\"Y'P8wyjARsn2+E.~7lAf{>o(Z|?EbP&rF^>>Q3wiyP,}sas1\"OSi^2W(J)t$"),
         "cb23abfd0e962073a9ab2e5ad2bfe778cc78493a7dc8ba31d0df63d0de5018e73aa2c442b27c7dd9f156671d3ea19142",
         HashAlgo.SHA384SUM);
      stringList.add(htd_String_198);
      
      HashTestData<? extends Object> htd_String_199 = new HashTestData<String>(
         new String("g3&ElAY%T(JQEH|k{D~zDXoxPqA\"R<y5oE>w#IOc4%%xD'x|y9@OM;_F/gi1<_}]#7%\"Y'P8wyjARsn2+E.~7lAf{>o(Z|?EbP&rF^>>Q3wiyP,}sas1\"OSi^2W(J)t$"),
         "3025fd1e1d0c43390553e15bf21d17d92c2a70343d463f016c0a4ba074a6dd5a6bb033bade4261339c7ed25a81fd6e66ac4a23633f8becf27db2edf96fa091c4",
         HashAlgo.SHA512SUM);
      stringList.add(htd_String_199);
   }
}
